############################
# @author EliasDH Team     #
# @see https://eliasdh.com #
# @since 21/08/2026        #
############################
---
apiVersion: v1
kind: Secret
metadata:
  name: zizisbe-secret
  namespace: zizisbe
type: Opaque
stringData:
  GHCR_TOKEN: "${GHCR_TOKEN}"
  GH_PAT: "${GH_PAT}"
  ELIASDH_API_KEY: "${ELIASDH_API_KEY}"
---